// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kanhbbifibboupngxkmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbmhiYmlmaWJib3Vwbmd4a210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzczOTAsImV4cCI6MjA2NDUxMzM5MH0.vx84lfu4WwernwsaPG4zLVfiNLKLbr3eqP1hTT7NMkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);